# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.0
maven_group = wuritz.bcc
archives_name = better-creeper-consent
enabled_platforms = fabric,neoforge
kotlin_version = 2.3.20

# Minecraft properties
minecraft_version = 26.2

# Dependencies
architectury_api_version = 21.0.7
fabric_loader_version = 0.19.3
fabric_api_version = 0.158.0+26.2
neoforge_version = 26.2.0.52-beta
fabric_kotlin_version = 1.13.13+kotlin.2.4.10
forge_kotlin_version = 6.3.0