org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

org.gradle.configuration-cache=false

minecraft_version=26.1.2
loader_version=0.19.2
loom_version=1.16-SNAPSHOT
fabric_kotlin_version=1.13.13+kotlin.2.4.10

mod_version=1.3.0-26.1.x
maven_group=wuritz.bcc

# Dependencies
fabric_api_version=0.149.1+26.1.2
