org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties
minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.64

## Mod Properties

mod_id=better_creeper_consent
mod_name=Better Creeper Consent
mod_license=MIT
mod_version=1.4.0+neoforge
mod_group_id=wuritz.bcc
