modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "better_creeper_consent"
version = "${version}"
displayName = "Better Creeper Consent"
authors = "wuritz"
iconFile = "icon.png"
description = '''
This is an example description! Tell everyone what your mod is about!
'''

[[dependencies.better_creeper_consent]]
modId = "neoforge"
type = "required"
versionRange = "[26.2.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.better_creeper_consent]]
modId = "minecraft"
type = "required"
versionRange = "[26.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.better_creeper_consent]]
modId = "architectury"
type = "required"
versionRange = "[21.0.7,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.better_creeper_consent]]
modId = "kotlinforforge"
type = "required"
versionRange = "[6.3.0,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "better-creeper-consent.mixins.json"
